jennybc/happy-git-with-r

04_install-pep-talk.Rmd
it looks like bookdown makes all tables 100% width by default so we need to have very specific CSS to target the table
=> fix operating systems stats table width

45_prompt-search-github.Rmd
not all people on github. These tips are super-helpful, by the way. Thanks for putting them here!
=> user:cran only searches the CRAN mirror

81_github-api-tokens.Rmd, _bookdown.yml
First take on including adopting material on GitHub API tokens. Currently in appendix.  I could link to it from one of the other sections, but wasn't sure which one.
Closes #31
=> Add appendix section about storing GitHub API tokens

81_github-api-tokens.Rmd
Somebody actually used this and discovered a pretty critical typo!
=> Fix typo in GITHUB_PAT instructions

07_install-git.Rmd
As per [this issue](https://github.com/jennybc/happy-git-with-r/issues/67#issuecomment-344072040), I have added a note to the installation guide for Windows users. It tells them they *must* select "Use Git from the Windows Command Prompt" during installation.
=> Added important installation note for Windows users.

50_more-content.Rmd
This url does not seem to be available anymore: https://help.github.com/articles/types-of-collaborative-development-models/
=> link at l.124 not working

12_connect-ssh-keys.Rmd
=> makes explicit the call to git2r::cred_ssh_key()

32_workflow-make-github-repo-browsable.Rmd
As per issue #81. I have suggested some paragraphs. 
I also tested whether it is true that "For simpler conversions between the different markdown flavours supported by Pandoc (mmd, php_extra and strict), you can convert these to Github using the Rstudio gui by simply renaming their extension to .Rmd". It does appear to be true that this leads to better formatted markdown, at least with the extension .md
Couldn't find a decent list of markdown editors so I have dropped that.
Feel free to take or leave, of course.
=> Converting other document formats into github markdown

60_article-make-github-repo-browsable.Rmd
* Update that RawGit is no-more in GH browsability chapter (same as https://github.com/STAT545-UBC/STAT545-UBC.github.io/pull/73).
* Note: I did _not_ rebuild the book, so this is just the Rmd.
=> Update RawGit status

.travis.yml
Good grief this was aggravating! I concluded that eliminating quotes entirely was unfortunately the best option. Even when properly escaped, `netlify deploy` barfed on unbalanced quotes, i.e if taking the first 50 characters retained only the opening quote (which doesn't seem correct, but is also not worth worrying about).
I think we want: take the first line of the commit message, get rid of tricky characters, truncate.
I would appreciate any clean up that screams out at you.
Resources consulted:
https://www.tldp.org/LDP/abs/html/string-manipulation.html
https://unix.stackexchange.com/questions/379181/escape-a-variable-for-use-as-content-of-another-script
This sounds perfect:
```
${parameter@operator}
The expansion is either a transformation of the value of parameter or information about …
```
=> Get rid of single and double quotes in the netlify message

git-remotes.Rmd, notes-ideas.Rmd, prompt-search-github.Rmd
Fixes #117, in which it appears these links cause problems rendering the book to PDF
=> Remove a challenging character from search links

install-git.Rmd
GitHub Desktop is no longer a way to install Git directly, but rather relies on the system Git and prompts users to install Git if they haven't already done so.
Here's the "Set up Git" page of GitHub's docs that describes the process as well: https://help.github.com/en/articles/set-up-git
Hopefully this is helpful - happy to answer any questions if you have them (disclosure: I work for GitHub).
=> Removed GitHub Desktop as a method to install Git

usage-rmd-and-github.Rmd
Looks like the content has moved! Updating the link accordingly.
=> Update GitHub repo browsability link

usage-new-project-github-first.Rmd
Closes #45
Since most of the steps are the same regardless of the platform, I just added a new GitLab/Bitbucket subsection when needed. Happy to hear your comments!
=> Add instructions to create repo from Gitlab or Bitbucket

usage-existing-project-github-last.Rmd
Changed "set the existing directory as the current project with proj_set(), then do usethis::use_rstudio()" to "usethis::create_project()" as use_rstudio is mainly intended for internal use.
=> Use create_project instead of use_rstudio

install-git-client.Rmd, install-git.Rmd
Closes #136 
This updates the description of GitHub Desktop to remove the portion that referred to the old version of the app, along with a value proposition for people likely using this guide. 😄
=> Update GitHub Desktop Git client description

references.Rmd
It [appears](https://github.com/git/git-scm.com/issues/1239) as if Try Git is no longer available. I've replaced it with another beginner-friendly tool: [Oh My Git!](https://ohmygit.org/), which I think fulfils a similar role.
=> replace Try Git with Oh My Git!

remote-setups-common.Rmd
Fixes #214 
previously: fix typo #214
=> Fix typo git remote clone to git clone

install-introduce-self-git.Rmd
You might want to test this on other devices/OSs, and if this doesn't work across the board then there should be a note that different quotes are needed based on your OS.
I'm on a freshly reformatted Windows 10 Pro, using the classic Windows Command Prompt, and I noticed that when using single quotes, the value gets cut off at whitespace:
```cmd
C:\Users\Dean>git config --global user.name 'Jane Doe'
C:\Users\Dean>git config --global --list
user.name='Jane
C:\Users\Dean>git config --global --unset-all user.name
C:\Users\Dean>git config --global user.name "Jane Doe"
C:\Users\Dean>git config --global --list
user.name=Jane Doe
```
=> git config commands need double quotes instead of single quotes

remote-setups-common.Rmd, remote-setups-equivocal.Rmd, render-r-script-demo.md, workflows-upstream-changes-into-fork.Rmd
Hi Jenny! Love this book so much and use it more frequently these days.
I noticed images not rendering in these chapters. Html was in their place. The culprit seems to be nested double quotes in the fig.alt chunk options. I changed those to single quotes. The images now render when I  build.
=> Image render fix for chapters 25, 26, and 32

install-r-rstudio.Rmd
Changed RStudio installation link to actual Posit link and eliminated references to RStudio preview, that seems still isn't available in Posit's new site.
=> Changing Rstudio installation source

connect-https-pat.Rmd
Hi - I am so thankful for this resource. 
A minor suggestion, which is to change the gitcreds::gitcreds_set() code in chapter 9 so that it can actually be copied straight into R. As of right now, the function and resulting dialogue is copied, which is a bit annoying if you're trying to paste into the R console. Please feel free to decline.
=> Minor suggestion for connect-https-pat.Rmd to allow easy copy/paste of gitcreds_set()
