12_connect-ssh-keys.Rmd
There are still formatting issues (which I had with masters of data science setup as well)
=> shell ssh keys

01_overview.Rmd, 03_workshops.Rmd, 05_install-github-acct.Rmd, 11_connect-credential-caching.Rmd, 15_install-connect-troubleshooting.Rmd, 20_usage-new-project-github-first.Rmd, 21_usage-existing-project-github-first.Rmd, 22_usage-existing-project-github-last.Rmd, 30_usage-first-use-rmd-and-github.Rmd, 31_usage-first-use-r-script-and-github.Rmd, 40_prompt-clone.Rmd, 44_prompt-practice-resets.Rmd, 50_more-content.Rmd, 99_sample.Rmd, README.md, packages.bib
I used RStudio's built in spell checker. I tried to only change things that were "obviously" typos - don't worry, I don't think there are any US-English to proper-English changes ;)
=> Spell check .Rmd and .md files, rebuilt book

32_workflow-make-github-repo-browsable.Rmd
I tried many ways to get this to work, and it would have been helpful if someone told me that I would not succeed ;)
=> Add note about HTML not working in private repos

01_overview.Rmd
* "way way" to "way"
* "R and with Git" to "R with Git"
=> Fixed a couple of typos in 01_overview.Rmd

08_install-introduce-self-git.Rmd, 10_connect-git-github.Rmd
Replace less with cat for terminal-novices. Alternatively, could introduce nano.
=> changing less to cat for ease of use

88_comic-relief.Rmd
Add ohshitgit to comic relief, sub-section "If you can tolerate adult language..."
=> Add ohshitgit.com to comic relief

05_install-github-acct.Rmd
Add (completely unnecessary) example to making username timeless: JennyFromTheBlock
=> Add example to making username timeless

46_prompt-git-branches.Rmd
This mostly adapted from Git Basic Branching and Merging, but we might want to change the example to be R code for happy git?
=> Add chapter on branching

03_workshops.Rmd, 46_prompt-pull.Rmd, _bookdown.yml
FYI @jimhester
This looks pretty complementary to the PR re: branch basics and therefore good for a possible workflow on day 2.
=> Git pull workflows

36_git-remotes.Rmd
FYI @jimhester. I'm going to merge. I think these are fairly non-controversial edits/additions.
=> Edits re: remotes

22_usage-existing-project-github-last.Rmd, 81_github-api-tokens.Rmd
Also add reference to how to set up PAT in Ch. 22
Closes #78
=> Use usethis to find .Renviron for GH PAT setup

index.Rmd
Hi Jenny,
I believe this will enable a twitter card for the site now, we can check the deployed version here:
https://cards-dev.twitter.com/validator
Alison
=> add url and cover-image to index.Rmd YAML (for twitter card)

install-github-acct.Rmd, usage-existing-project-github-last.Rmd
PR to resolve #112. Feedback welcomed.
=> Update documentation for Github private repositories

connect-can-rstudio-use-git.Rmd, connect-intro.Rmd, prompt-fork-pr-bingo.Rmd, prompt-fork.Rmd
Co-authored-by: mkkkt <bmfd.2011@gmail.com>
Co-authored-by: MoPau <44197606+MoPau@users.noreply.github.com>
Co-authored-by: moco <momoko@faustud-010-021-031-083.pool.uni-erlangen.de>
Co-authored-by: Adele <44588279+aDeLe24@users.noreply.github.com>
Co-authored-by: Elen93 <40487564+Elen93@users.noreply.github.com>
Co-authored-by: t-rop <44171964+t-rop@users.noreply.github.com>
=> fix some typos and grammar

references.Rmd
I read this a few years ago, and it broadened by perspective.  Consider including it.
=> Include *Team Geek* book

workflows-make-github-repo-browsable.Rmd
=> Update CLICK HERE to suggest an edit link

notes-classroom-overview.Rmd
Additional space - a typo mistake.
=> Correction on notes-classroom-overview.Rmd

usage-rmd-and-github.Rmd
RawGit will soon shutdown "If you're currently using RawGit, please stop using it as soon as you can."
=> Removed RawGit

usage-rmd-and-github.Rmd
Added the R command to check RStudio version
=> Added command to check RStudio version

connect-can-rstudio-use-git.Rmd, connect-troubleshooting.Rmd, install-git-client.Rmd, usage-existing-project-github-last.Rmd, workflows-fork-and-clone.Rmd, workflows-repeated-amend.Rmd, workflows-upstream-changes-into-fork.Rmd
Closes https://github.com/jennybc/happy-git-with-r/issues/127
=> cross referenced 'shell' where not referenced when mentioned in chapter. 

install-github-acct.Rmd
Add to username advice about not using uppercase letters in usernames. Closes #152.
=> Add advice about avoiding uppercase letters in usernames

connect-credential-caching.Rmd
Removed comma and added parentheses.
=> Fixed typo 

index.Rmd
Thanks for writing the book. Learned a lot.
=> fix a typo in index

install-introduce-self-git.Rmd
I was confused initially on reading these about what "these commands" were referencing. Updated the wording to mention the previous section and two specific commands called.
=> Minor update to language to increase clarity around "these commands" in 7.1
